[MQTT] 
    broker = localhost 
    port = 1883 
    topic_prefix = /POLOA/ 

[BUILDING] 
    id = POLOA 

[DATASET] 
    dir = ./data/raw_dataset 
    sensor_id = 1 

[SENSOR_INTERVALS] #in seconds
    co2 = 1 
    humidity = 1 
    temperature = 1 
    luminosity = 1 
    pir = 2

[MAPPING]
    mapping_file = data/sensor_mapping_master.csv

[KAFKA]
    topic = iot_sensors
    BROKER_URL = localhost:9092


[THINGSBOARD]
    TB_URL = http://localhost:9191
    TB_USERNAME = tenant@thingsboard.org 
    TB_PASSWORD = tenant
    CSV_FILE_PATH = data/sensor_mapping_master.csv
    THINGSBOARD_PORT = 1884
    THINGSBOARD_HOST = localhost
    GATEWAY_TOKEN = Ps22nNj8nnPIhqjRLVsE
    TOPIC_GATEWAY = v1/gateway/telemetry

[MONGO]
    uri = mongodb://mongo:27017
    database = building_iot
    collection = aggr_iot_metrics