[MQTT] 
    broker = localhost 
    port = 1883 
    topic_prefix = /POLOA/ 

[BUILDING] 
    id = POLOA 

[DATASET] 
    dir = ./data/raw_dataset 
    sensor_id = 1 

[SENSOR_INTERVALS] #in seconds
    co2 = 5 
    humidity = 5 
    temperature = 5 
    luminosity = 5 
    pir = 10
