

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    volumes:
      - ./zookeeper_data:/var/lib/zookeeper/data
    networks:
      - iot-network
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 10s
      timeout: 5s
      retries: 3
    
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - iot-network
    healthcheck:
      test: kafka-broker-api-versions --bootstrap-server localhost:9092
      interval: 10s
      timeout: 10s
      retries: 5
    
  kafka-init:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-init
    depends_on:
      - kafka
    networks:
      - iot-network
    entrypoint: ["/bin/bash", "-c"]
    command: |
      "
      echo '=== Aspetto che Kafka sia pronto ===';
      sleep 10;
      echo '=== Creazione topic iot_sensors ===';
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic iot_sensors --partitions 1 --replication-factor 1;
      echo '=== Verifica topics creati ===';
      kafka-topics --bootstrap-server kafka:9092 --list;
      echo '=== Inizializzazione completata ===';
      "

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      # Credenziali e configurazione di InfluxDB 2.x
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=poloa_admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=POLOA_org
      - DOCKER_INFLUXDB_INIT_BUCKET=temporal_datalake # Il bucket che riceverà i dati
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-influxdb-token # Necessario per il connettore Sink
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
    networks:
      - iot-network


  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.5.0
    container_name: kafka-connect
    depends_on:
      kafka:
        condition: service_healthy
      mqtt_broker:
        condition: service_started
      influxdb:
        condition: service_started
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_GROUP_ID: "connect-cluster"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      CONNECT_LOG4J_LOGGERS: "org.reflections=ERROR"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xms256M -Xmx512M"
    volumes:
      - ./kafka-connect-plugins:/usr/share/confluent-hub-components
      - ./connectors:/connectors
    networks:
      - iot-network
    
  init-connectors:
    image: curlimages/curl:latest
    container_name: init-connectors
    depends_on:
      - kafka-connect
    volumes:
      - ./init-connectors.sh:/init-connectors.sh
      - ./connectors:/connectors
    entrypoint: ["sh", "/init-connectors.sh"]
    networks:
      - iot-network
      
  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    networks:
      - iot-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 3
      
  spark:
    image: apache/spark:3.5.0
    container_name: spark
    user: root
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
      - ./spark-app:/app
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    depends_on:
      kafka:
        condition: service_healthy
      mongo:
        condition: service_healthy
    networks:
      - iot-network
      
  spark-job:
    build: ./spark-app
    container_name: spark-job
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      mongo:
        condition: service_healthy
    volumes:
      - ./spark-app:/app
    networks:
      - iot-network
    restart: on-failure
    entrypoint: >
      sh -c "
      echo '=== Verifica topic Kafka ===';
      kafka-topics --bootstrap-server kafka:9092 --list;
      echo '=== Avvio Spark Job ===';
      /opt/spark/bin/spark-submit
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0
      /app/spark_main.py
      "

  spark-batch:
    build: ./spark-app
    container_name: spark-batch
    depends_on:
      influxdb:
        condition: service_started
      mongo:
        condition: service_healthy
    volumes:
      - ./spark-app:/app
    networks:
      - iot-network
    restart: "no"
    # Mantains the container on container acceso but in idle state
    entrypoint: [ "tail", "-f", "/dev/null" ]

  #it wakes up the spark-batch container to run scheduled jobs
  scheduler:
    image: mcuadros/ofelia:latest
    container_name: scheduler
    depends_on:
      - spark-batch
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - iot-network


  streamlit:
    build: ./streamlit-app
    container_name: streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit-app:/app
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - iot-network
      
  mqtt_broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge