[SCHEMA]
# The message fields  defines the format of the message received by spark 
message_fields = timestamp:long,building:string,floor:string,room:string,sensor_type:string,sensor_id:string,value:double
