[PATHS]
schema_path = /spark-app/configuration/schema.conf


#Kafka port, the topic and it only reads the last messages  
[KAFKA]
bootstrap_servers = kafka:9092
topic = iot_sensors
startingOffsets = latest

#windows size and the metrics to calculate
[AGGREGATION]
window_size = 10 minutes
metrics = min,max,avg

# the db port, name of the collection
[MONGO]
uri = mongodb://mongo:27017
database = building_iot
collection = iot_metrics