[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  flush_interval = "5s"
  omit_hostname = true

[[inputs.kafka_consumer]]
  brokers = ["kafka:9092"]
  topics  = ["iot_sensors"]
  consumer_group = "telegraf-influx-sink"
  offset = "oldest"

  data_format = "json"

  json_time_key = "timestamp"
  json_time_format = "unix"

  tag_keys = ["building","floor","room","sensor_type","sensor_id","device"]

  name_override = "iot_telemetry"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "my-influxdb-token"
  organization = "POLOA_org"
  bucket = "temporal_datalake"

